enum Vocation : u8 {
  Guardian      = 0,
  Warrior       = 1,
  Priest        = 2,
  Mage          = 3,
  MartialArtist = 4,
  Thief         = 5,
  Minstrel      = 6,
  Gladiator     = 7,
  Armamentalist = 8,
  Paladin       = 9,
  Sage          = 10,
  Luminary      = 11,
  Ranger        = 12,
};

enum Item : u16 {
    WonderHelm = 12170,
    HeavenlyHelm = 12171,
    RagingBullHelm = 12180,
    MinotaurHelm = 12181,
    GreatHelm = 12182,
    VeteransHelm = 12183,
    SkullHelm = 12184,
    LiquidMetalHelm = 12185,
    MetalKingHelm = 12186,
    RustyHelmet = 12187,
    HallowedHelm = 12188,
    BlessedHelm = 12189,
    IronHelmet = 12191,
    RagnarsHelm = 12192,
    AlefgardHelm = 12193,
    ErdricksHelmet = 12194,
    MidenhallHelm = 12195,
    MetalSlimeHelm = 12197,
    SteelHelmet = 12198,
    GigasteelHelmet = 12199,
    FeatherHeadband = 12200,
    Circlet = 12201,
    BattlersBand = 12202,
    RavishingRibbon = 12204,
    Hairband = 12205,
    CrownOfClarity = 12206,
    SteelySweatband = 12207,
    SilverTiara = 12208,
    GoldenTiara = 12209,
    GoldCirclet = 12211,
    StarCirclet = 12212,
    AliahanHeadpiece = 12290,
    SpellwardCirclet = 12291,
    ZenithianHelm = 12292,
    ThinkingCap = 12295,
    ScholarsCirclet = 12296,
    WarriorsHelm = 12400,
    HocusHat = 12401,
    HermeticHat = 12402,
    MusketeerHat = 12403,
    CavalierHat = 12404,
    MinervasMitre = 12405,
    CannyCap = 12406,
    HuntersHat = 12407,
    EarCosy = 12408,
    TopHat = 12409,
    Bandana = 12410,
    HardwoodHeadwear = 12411,
    SunCrown = 12412,
    ApollosCrown = 12413,
    TrailblazingBandana = 12414,
    MercurysBandana = 12415,
    FeatheredCap = 12416,
    MagicalHat = 12417,
    MegamagicalHat = 12418,
    WitchsHat = 12419,
    UnhappyHat = 12420,
    HappyHat = 12421,
    SpringBreezeHat = 12422,
    SummerCloudHat = 12423,
    AutumnShowerHat = 12424,
    WinterSkyHat = 12425,
    KirylsKamilavka = 12426,
    SantasHat = 12428,
    HolyHat = 12429,
    TornekosCap = 12430,
    YangussTitfer = 12431,
    ErinnsHeadkerchief = 12432,
    TiptopTopper = 12433,
    ProperTopper = 12434,
    SwashbucklersBonnet = 12436,
    Mitre = 12480,
    TrodainBandana = 12491,
    GothanTurban = 12492,
    EstardHood = 12493,
    AlenasHat = 12494,
    Turban = 12495,
    PointyHat = 12496,
    SlimeCrown = 12497,
    LeatherHat = 12498,
    WizardsHat = 12499,
    ThugsMug = 12500,
    Trodeface = 12501,
    PumpkinHead = 12502,
    SkullCap = 12503,
    TrickyTurban = 12600,
    ThiefsTurban = 12700,
    DisturbinTurban = 12701,
    MailCoif = 12702,
    MoonbrookeHood = 12780,
    MaribelsHood = 12781,
    DragonWarriorHelm = 12785,
    IronMask = 12790,
    FiligreeMask = 12791,
    PlatinumHeadgear = 12792,
    MythrilCoif = 12793,
    HadesHelm = 12794,
    MythrilHelm = 12795,
    FurHood = 12796,
    Slood = 12797,
    BunnyEars = 12800,
    CatEars = 12801,
    PhantomMask = 12802,
    StellarStarflower = 12803,
    FleurettesFloret = 12804,
    Halo = 12805,
    DeborasDamasks = 12806,
    MalleableMask = 12807,
    PapillonMask = 12808,
    MaidsMop = 12809,
    SilkenVeil = 12810,
    SupernaturalSpecs = 12811,
    SharpShades = 12812,
    MonarchicMoustache = 12813,
    XraySpecs = 12814,
    SilverSpecs = 12815,
    SomniaHair = 12900,
    CannockHelm = 12901,
    BoryasBouffant = 12902,
    MayasMane = 12903,
    MeenasMane = 12904,
    BiancasBraid = 12907,
    NerasHair = 12908,
    CarversHair = 12909,
    MillysHair = 12910,
    AshlynnsHair = 12911,
    KiefersHair = 12912,
    JesssTresses = 12913,
    TemplarsTresses = 12914,
    MorriesMullet = 12915,
    BrownAfro = 12916,
    RedAfro = 12917,
    WarriorsArmour = 13000,
    TusslersTop = 13001,
    FlamencoShirt = 13002,
    FurVest = 13003,
    StarsSuit = 13004,
    PlainClothes = 13005,
    TrainingTop = 13006,
    CelestialSuit = 13007,
    SwinedimplesBlazer = 13009,
    TracksuitTop = 13010,
    GarishGarb = 13011,
    CloakOfEvasion = 13012,
    CloakOfConcealment = 13013,
    GooeyGear = 13014,
    SmartSuit = 13015,
    SuperstarsSuit = 13016,
    DragonTop = 13017,
    CombatTop = 13018,
    TwinklingTuxedo = 13020,
    Tropotoga = 13021,
    Startotoga = 13022,
    Mesotoga = 13023,
    Exotoga = 13024,
    CarversVest = 13025,
    KiefersClothes = 13026,
    YangussBilly = 13027,
    GustoGarb = 13028,
    MuscleBelt = 13031,
    BestVest = 13032,
    Glombolero = 13033,
    AquilasArmour = 13034,
    WhiteTuxedo = 13035,
    SantaSuit = 13036,
    SkeletonSuit = 13037,
    CaptainsCoat = 13038,
    WhiteTshirt = 13039,
    JollyRogerJumper = 13040,
    ShipmatesShirt = 13041,
    MidenhallGarb = 13080,
    WayfarersClothes = 13095,
    TrodainTogs = 13096,
    SomniaClothes = 13097,
    EstardClothes = 13098,
    ZenithianClothes = 13099,
    TacticalVest = 13100,
    LeatherArmour = 13101,
    ScaleArmour = 13102,
    ChainMail = 13103,
    MythicalArmour = 13160,
    LegendaryArmour = 13161,
    DragonWarriorArmour = 13162,
    SacrosanctArmour = 13170,
    VeteransArmour = 13171,
    MirrorArmour = 13172,
    CatoptricArmour = 13173,
    GigantArmour = 13174,
    LiquidMetalArmour = 13175,
    MetalKingArmour = 13176,
    RustyArmour = 13177,
    VictoriousArmour = 13178,
    GloriousArmour = 13179,
    SilverMail = 13180,
    GoldMail = 13181,
    PlatinumMail = 13182,
    HeavyArmour = 13183,
    MagicArmour = 13184,
    EnchantedArmour = 13185,
    EtherealArmour = 13186,
    DragonMail = 13187,
    SpikedArmour = 13188,
    SacredArmour = 13189,
    MetalSlimeArmour = 13190,
    IronArmour = 13192,
    RagnarsArmour = 13193,
    AlefgardArmour = 13194,
    ErdricksArmour = 13195,
    LargescaleArmour = 13196,
    BronzeArmour = 13197,
    FullPlateArmour = 13198,
    GigasteelArmour = 13199,
    HolyMail = 13200,
    FencingFrock = 13201,
    NomadicDeel = 13202,
    LeatherCape = 13203,
    FurPoncho = 13204,
    VelvetCape = 13205,
    MajesticMantle = 13206,
    DarkRobe = 13207,
    MacabreMantle = 13208,
    PalliumRegale = 13209,
    CapeOfGoodKarma = 13210,
    TemplarsTogs = 13211,
    AliahanClothes = 13290,
    GothanRobe = 13291,
    DivineDress = 13292,
    AsceticRobe = 13300,
    RoguesRobes = 13301,
    RoguesssRobes = 13302,
    FencingJacket = 13303,
    SagesRobe = 13304,
    SilkRobe = 13305,
    RobeOfSerenity = 13306,
    NightmareGown = 13307,
    CelestriasGown = 13308,
    CelestriasRaiment = 13309,
    DragonRobe = 13310,
    XenlonRobe = 13311,
    AngelsRobe = 13312,
    ArchangelsRobe = 13313,
    AeonsRobe = 13314,
    SeraphsRobe = 13315,
    KirylsClothes = 13316,
    BoryasRobe = 13317,
    TornekosClothes = 13318,
    TrodesRobes = 13320,
    RobeOfSweetDreams = 13324,
    MagicalRobes = 13325,
    EnchantedRobes = 13326,
    EtherealRobes = 13327,
    SaintlyRobe = 13328,
    FlowingDress = 13329,
    WizardsRobe = 13390,
    WitchsRobe = 13391,
    Surplice = 13490,
    CannockCloak = 13491,
    Strongsam = 13500,
    PriestesssPinafore = 13501,
    DancersDress = 13502,
    MaidensMantle = 13503,
    SpangledDress = 13504,
    DragonDress = 13505,
    ShimmeringDress = 13506,
    QueensRobe = 13507,
    EmpresssRobe = 13508,
    PrincesPeaCoat = 13509,
    KingsCoat = 13510,
    EmperorsAttire = 13511,
    MoonbrookeDress = 13513,
    MeenasRobe = 13514,
    NerasDress = 13515,
    MillysClothes = 13516,
    MaribelsClothes = 13517,
    JessicasFrock = 13518,
    LeatherDress = 13519,
    PlainDress = 13520,
    SummerDress = 13521,
    Jaguarment = 13522,
    PrincesssRobe = 13590,
    FizzleretardantBlouse = 13600,
    FemiscyranMail = 13601,
    BrawlingByrnie = 13602,
    HolyFemail = 13603,
    TinttasticTutu = 13604,
    DancersCostume = 13605,
    BunnySuit = 13606,
    TechnicolourTutu = 13607,
    DangerousBikiniTop = 13608,
    HotBikiniTop = 13609,
    SizzlingBikiniTop = 13610,
    DangerousBustier = 13612,
    SilkBustier = 13613,
    DivineBustier = 13614,
    MayasOutfit = 13615,
    BiancasClothes = 13616,
    AshlynnsClothes = 13617,
    StellarSuit = 13618,
    FleurettesFrock = 13619,
    MaidOutfit = 13620,
    DeborasDress = 13621,
    ErinnsOutfit = 13622,
    PattysDirndl = 13623,
    SellmasFrock = 13624,
    WeddingDress = 13625,
    SantasLittleHelperSuit = 13626,
    CombatCostume = 13627,
    ZenithianLeotard = 13695,
    AlenasDress = 13696,
    FizzleretardantSuit = 13700,
    FizzleproofSuit = 13701,
    IronCuirass = 13790,
    TortoiseShell = 13791,
    SilverCuirass = 13793,
    TortoiseshellArmour = 13794,
    WarriorsGloves = 15000,
    GorgeousGloves = 15001,
    MentalMittens = 15002,
    CottonGloves = 15003,
    LinenGloves = 15004,
    LeatherGloves = 15005,
    RiotousWristbands = 15007,
    BlessedBindings = 15008,
    RubberGloves = 15009,
    WayfarersGloves = 15010,
    MayoresssMittens = 15013,
    MarquesssMittens = 15014,
    MonarchsMittens = 15015,
    VeteransGloves = 15016,
    EnchantresssGloves = 15017,
    MinistersMittens = 15018,
    GlommersGloves = 15019,
    GurusGloves = 15020,
    GloomyGloves = 15021,
    MurkyMittens = 15022,
    MatadorsGloves = 15023,
    ApprenticesGloves = 15024,
    MastersGloves = 15025,
    GrandmastersGloves = 15026,
    GodlyGloves = 15027,
    ZenithianGauntlet = 15028,
    GothanWristbands = 15029,
    MayasBracelets = 15030,
    MeenasBracelets = 15031,
    HeavyHandwear = 15032,
    SilverBracelets = 15033,
    BiancasBracelets = 15034,
    NerasBracelets = 15035,
    CarversBracers = 15036,
    MillysBracers = 15037,
    AshlynnsGloves = 15038,
    UltramarineMittens = 15039,
    BlindinBracers = 15040,
    AngelosGloves = 15041,
    GrandissimoGloves = 15042,
    BattlersBracers = 15043,
    Einhander = 15045,
    CrimsonGauntlets = 15047,
    LockpickersMitts = 15048,
    KiefersGloves = 15091,
    AlefgardGloves = 15092,
    MidenhallGloves = 15093,
    CannockGloves = 15094,
    AliahanGloves = 15095,
    McryansMittens = 15096,
    AlenasGloves = 15097,
    FingerlessGauntlets = 15100,
    BruisersBracers = 15101,
    FemiscyranFingerwear = 15102,
    MetallicMitts = 15103,
    LightGauntlets = 15105,
    ArchersArmguard = 15106,
    SturdyGauntlets = 15107,
    HeavyGauntlets = 15108,
    FingerlessGloves = 15109,
    SomniaGloves = 15190,
    LeatherGauntlets = 15200,
    EtherealGloves = 15280,
    RustyGauntlets = 15281,
    VestaGauntlets = 15282,
    DianaGauntlets = 15283,
    TempestesGauntlets = 15284,
    SolInvictusGauntlets = 15285,
    DragonWarriorGloves = 15286,
    IronGauntlets = 15291,
    ErdricksGauntlets = 15292,
    SteelGauntlets = 15293,
    GigasteelGauntlets = 15294,
    MetalSlimeGauntlets = 15295,
    LiquidMetalSlimeGloves = 15296,
    MetalKingSlimeGloves = 15297,
    MagicMittens = 15298,
    EnchantedGloves = 15299,
    SomniaShorts = 16093,
    BoxerShorts = 16094,
    LeatherKilt = 16095,
    FemiscyranBottoms = 16100,
    ChainmailSocks = 16103,
    PopSocks = 16104,
    ZenithianLeggings = 16191,
    WarriorsTrousers = 16200,
    NickersKnickers = 16202,
    TusslersTrousers = 16203,
    WizardsTrousers = 16204,
    LoudTrousers = 16205,
    BattleBritches = 16206,
    SwordsmansSlacks = 16207,
    RedTights = 16208,
    GreenTights = 16209,
    SteppeSteppers = 16210,
    BlessedBottoms = 16211,
    WhiteTights = 16212,
    CottonTrousers = 16213,
    TrainingTrousers = 16214,
    CelestialStockings = 16215,
    BoomerBriefs = 16216,
    WonderPants = 16217,
    IronKneecaps = 16218,
    SteelKneecaps = 16219,
    GigasteelKneecaps = 16220,
    FancyPants = 16221,
    TransparentTights = 16222,
    DragonTrousers = 16223,
    CombatTrousers = 16224,
    TantricTrousers = 16228,
    SturdySlacks = 16229,
    ImpregnableLeggings = 16230,
    InvincibleTrousers = 16231,
    ImmortalTrousers = 16232,
    EternityTrousers = 16233,
    InfinityTrousers = 16234,
    CannockTrousers = 16235,
    KirylsTrousers = 16236,
    TornekosTrousers = 16237,
    CarversShorts = 16240,
    MillysPants = 16241,
    KiefersTrousers = 16243,
    CorBlimeyTrousers = 16244,
    PassionTights = 16245,
    StellarStockings = 16246,
    FleurettesChaussettes = 16248,
    ToughieTrousers = 16251,
    TemplarsTrousers = 16252,
    TrackyBottoms = 16255,
    DragonWarriorTrousers = 16256,
    AquilasTrousers = 16257,
    SwinedimplesSlacks = 16258,
    WhiteTuxedoTrousers = 16259,
    SantasSlacks = 16260,
    SkeletalSlacks = 16261,
    PiratePantaloons = 16262,
    BlueJeans = 16263,
    TrinityTights = 16283,
    MidenhallTrousers = 16286,
    AlefgardTrousers = 16287,
    AliahanTrousers = 16288,
    ZenithianTrousers = 16289,
    EstardTrousers = 16290,
    TrodainTrousers = 16291,
    SorcerersSlacks = 16300,
    SlickSlacks = 16301,
    FishnetStockings = 16302,
    DangerousMidriffWrap = 16303,
    HotBikiniBottoms = 16304,
    SizzlingBikiniBottoms = 16305,
    SwinedimplesSkirt = 16306,
    RedSkirt = 16307,
    BlueSkirt = 16308,
    Kiltlet = 16309,
    MayasBottoms = 16310,
    DenimSkirt = 16311,
    BlueKnickers = 16312,
    BlackKnickers = 16313,
    SpringtimeSkirt = 16316,
    SnazzySkirt = 16317,
    MagicalSkirt = 16318,
    SeabreezeSkirt = 16319,
    AlenasTights = 16390,
    GothanGumboots = 17091,
    SomniaBoots = 17092,
    EstardShoes = 17093,
    ZenithianBoots = 17094,
    AliahanBoots = 17095,
    Trodainers = 17096,
    WarriorsBoots = 17100,
    FrugalFootwear = 17101,
    BanditBoots = 17102,
    Sneakers = 17103,
    KungFuShoes = 17104,
    WizardWellies = 17105,
    Acroboots = 17106,
    WuShoes = 17107,
    FemiscyranFootwear = 17108,
    CowboyBoots = 17109,
    HipBoots = 17110,
    SafetyShoes = 17111,
    CleverClogs = 17112,
    ShamanShoes = 17113,
    Agiliboots = 17114,
    HikingBoots = 17115,
    BardicBoots = 17116,
    CrimsonBoots = 17117,
    LeatherBoots = 17118,
    WellingtonBoots = 17119,
    CelestialShoes = 17120,
    ErinnsBoots = 17140,
    PattysPumps = 17141,
    AquilasBoots = 17142,
    WhiteWingtips = 17143,
    BlahnoloManiks = 17150,
    ChicChaussures = 17152,
    ThugBoots = 17155,
    BoryasBoots = 17158,
    Spellspadrilles = 17159,
    AshlynnsShoes = 17160,
    KiefersShoes = 17163,
    MaribelsShoes = 17164,
    TrodesTreads = 17165,
    BovverBoots = 17166,
    PoshPumps = 17167,
    TemplarBoots = 17168,
    CasanovaClogs = 17169,
    PixieBoots = 17170,
    TricksieBoots = 17171,
    MoonbrookeShoes = 17172,
    KirylsBoots = 17173,
    BiancasBoots = 17176,
    NerasBoots = 17177,
    CarversShoes = 17178,
    MillysShoes = 17179,
    BrahmanBoots = 17181,
    HerosBoots = 17182,
    BasilicBoots = 17183,
    EmperorsBoots = 17184,
    BootsOfBeatitude = 17185,
    SaferShoes = 17186,
    SafestShoes = 17187,
    DepressingShoes = 17188,
    ElevatingShoes = 17189,
    Valenki = 17191,
    AlefgardBoots = 17192,
    MidenhallBoots = 17193,
    CannockBoots = 17194,
    HobnailBoots = 17195,
    VeteransBoots = 17196,
    CombatBoots = 17197,
    ShemageShoes = 17198,
    BlessedBoots = 17199,
    PaybackPumps = 17300,
    SaintlySollerets = 17302,
    DragonWarriorBoots = 17303,
    IronSabatons = 17391,
    HighlandBoots = 17392,
    MetalSlimeSollerets = 17394,
    SteelSabatons = 17395,
    GigasteelSabatons = 17396,
    LiquidMetalSlimeBoots = 17397,
    MetalKingSlimeBoots = 17398,
    SirenSandals = 17400,
    ShefuShoes = 17401,
    SheepskinShoes = 17402,
    StarletSandals = 17403,
    LeatherShoes = 17404,
    Clogs = 17405,
    Sandals = 17406,
    ClassyClogs = 17407,
    HighHeels = 17408,
    StilettoHeels = 17409,
    HighnessHeels = 17410,
    GalvanisedGeta = 17411,
    SorceressSandals = 17412,
    HighclassHeels = 17413,
    SensibleSandles = 17414,
    SagaciousSandles = 17415,
    SapientSandals = 17416,
    SentientSandals = 17417,
    TornekosSandals = 17419,
    SattriyaSandals = 17420,
    SamhitaSandals = 17421,
    StrengthRing = 18000,
    ToughGuyTattoo = 18001,
    RagingRuby = 18002,
    MightyArmlet = 18003,
    GoldBracer = 18004,
    SlimeEarrings = 18005,
    DragonScale = 18006,
    GoldRing = 18007,
    RubyOfProtection = 18008,
    BunnyTail = 18009,
    PinkPearl = 18010,
    BowTie = 18011,
    UtilityBelt = 18012,
    AgilityRing = 18013,
    MeteoriteBracer = 18014,
    SorcerersRing = 18015,
    GoldRosary = 18016,
    Rosary = 18017,
    SorcerersStone = 18018,
    BrainyBracer = 18019,
    LifeBracer = 18020,
    SpiritBracer = 18021,
    MonarchicMark = 18022,
    PrayerRing = 18023,
    HolyTalisman = 18024,
    SoberRing = 18025,
    ContraBand = 18026,
    FullMoonRing = 18027,
    RousingRing = 18028,
    RingOfClarity = 18029,
    CatholiconRing = 18030,
    TerribleTattoo = 18031,
    SkullRing = 18032,
    ElfinCharm = 18033,
    LifeRing = 18034,
    GoddessRing = 18035,
    RecklessNecklace = 18038,
    LuckyPendant = 18039,
    VenusTear = 18040,
    SoldiersMedal = 18043,
    LifesavingMedal = 18044,
    MagerAchievement = 18045,
    MercuryPrize = 18046,
    HonourAmongThieves = 18047,
    WearwithallAward = 18048,
    CriticalAcclaim = 18049,
    OrderOfChivalry = 18050,
    CombatActionMedal = 18051,
    MedalOfFreedom = 18052,
    LegionOfMerit = 18053,
    Noscar = 18054,
    WeddingRing = 18055,
    ParingKnife = 19050,
    BronzeKnife = 19051,
    DivineDagger = 19052,
    PoisonMothKnife = 19053,
    BatterflyKnife = 19054,
    DreadDagger = 19055,
    PoisonNeedle = 19057,
    AssassinsDagger = 19058,
    IcicleDirk = 19059,
    FenrirFang = 19060,
    DeadlyNightblade = 19061,
    SwordBreaker = 19062,
    SoulBreaker = 19063,
    FalconKnifeEarring = 19064,
    Gladius = 19065,
    FlameTang = 19066,
    PruningKnife = 19067,
    DeftDagger = 19068,
    DartingDagger = 19069,
    DashingDagger = 19070,
    DynamoDagger = 19071,
    OakenClub = 19150,
    AceOfClubs = 19151,
    Sledgehammer = 19152,
    WarHammer = 19153,
    UberWarHammer = 19154,
    GiantWrench = 19155,
    TerraTamper = 19156,
    TerraFirmer = 19157,
    TerraHammer = 19158,
    MaraudersMaul = 19159,
    HelasHammer = 19160,
    GiantsHammer = 19161,
    TitansHammer = 19162,
    MegatonHammer = 19163,
    WarlordsHammer = 19164,
    Groundbreaker = 19165,
    Earthsplitter = 19166,
    Moonmasher = 19167,
    Starsmasher = 19168,
    WarriorsSword = 20000,
    BanditBlade = 20001,
    ValkyrieSword = 20002,
    Rapier = 20003,
    CopperSword = 20004,
    SoldiersSword = 20005,
    IronBroadsword = 20006,
    SteelBroadsword = 20007,
    GigasteelBroadsword = 20008,
    FizzleFoil = 20009,
    CauterySword = 20010,
    AuroraBlade = 20011,
    PlatinumSword = 20012,
    Dragonsbane = 20013,
    DragonSlayer = 20014,
    FalconBlade = 20015,
    UberFalconBlade = 20016,
    MiracleSword = 20017,
    UberMiracleSword = 20018,
    FireBlade = 20019,
    InfernoBlade = 20020,
    MetalSlimeSword = 20021,
    LiquidMetalSword = 20022,
    MetalKingSword = 20023,
    RustySword = 20024,
    ErdricksSword = 20025,
    StardustSword = 20026,
    NebulaSword = 20027,
    SupernovaSword = 20028,
    HypernovaSword = 20029,
    FeatherFan = 20100,
    IronFan = 20101,
    SteelFan = 20102,
    GigasteelFan = 20103,
    WarFan = 20104,
    FoehnFan = 20105,
    GaleForceFan = 20106,
    TortoiseshellFan = 20107,
    BlackTortoiseFan = 20108,
    FelineFan = 20109,
    WhiteTigerFan = 20110,
    FowlFan = 20111,
    VermillionBirdFan = 20112,
    CobraFan = 20113,
    AzureDragonFan = 20114,
    StellarFan = 20115,
    LunarFan = 20116,
    SolarFan = 20117,
    FriendlyFan = 20118,
    Attribeauty = 20119,
    CriticalFan = 20120,
    OvercriticalFan = 20121,
    HypercriticalFan = 20122,
    DireCriticalFan = 20123,
    WhiteBouquet = 20124,
    Battleaxe = 20200,
    ProsAxe = 20201,
    SteelAxe = 20202,
    GigasteelAxe = 20203,
    GoldenAxe = 20204,
    MoonAxe = 20205,
    FullMoonAxe = 20206,
    KaiserAxe = 20207,
    HeadsmansAxe = 20208,
    ExecutionersAxe = 20209,
    IceAxe = 20210,
    AvalancheAxe = 20211,
    HeavyHatchet = 20212,
    BadAxe = 20213,
    MaxiAxe = 20214,
    Climaxe = 20215,
    GalaxyAxe = 20216,
    KingAxe = 20291,
    IronAxe = 20293,
    LeatherWhip = 20300,
    ThornWhip = 20301,
    BattleWhip = 20302,
    SnakeskinWhip = 20303,
    SerpentineWhip = 20304,
    Sidewinder = 20305,
    ChainWhip = 20306,
    IronWhip = 20307,
    SpikedSteelWhip = 20308,
    GigaspikeWhip = 20309,
    DragontailWhip = 20310,
    DemonWhip = 20311,
    ArchdemonWhip = 20312,
    ScourgeWhip = 20313,
    QueensWhip = 20314,
    EmpresssWhip = 20315,
    GoddessWhip = 20316,
    WizardlyWhip = 20317,
    GringhamWhip = 20318,
    MegaGringhamWhip = 20319,
    GigaGringhamWhip = 20320,
    UberGringhamWhip = 20321,
    HieroglyphStaff = 20400,
    SagesStaff = 20401,
    BrouhahaBoomstick = 20402,
    OakStaff = 20403,
    StaffOfSentencing = 20404,
    StaffOfDivineWrath = 20405,
    StolosStaff = 20406,
    LightningConductor = 20407,
    WatermaulWand = 20408,
    TsunamiStaff = 20409,
    RuneStaff = 20410,
    MegamagicalMace = 20411,
    SceptreOfGitt = 20412,
    SavantsStaff = 20413,
    Wyrmwand = 20414,
    BrightStaff = 20415,
    ShiningStaff = 20416,
    BrilliantStaff = 20417,
    AuroraStaff = 20418,
    FaerieStaff = 20419,
    MagicalMace = 20493,
    WizardsStaff = 20494,
    LightningStaff = 20495,
    MagmaStaff = 20496,
    BambooLance = 20500,
    CelestialSpear = 20501,
    Partisan = 20502,
    IronLance = 20503,
    SteelLance = 20504,
    GigasteelLance = 20505,
    LongSpear = 20506,
    HolyLance = 20507,
    BattleFork = 20508,
    Trident = 20509,
    GracesTrident = 20510,
    SandstormSpear = 20511,
    Halberd = 20512,
    LightningLance = 20513,
    StormSpear = 20514,
    DemonSpear = 20515,
    HeroSpear = 20516,
    MetalSlimeSpear = 20517,
    LiquidMetalSpear = 20518,
    MetalKingSpear = 20519,
    Poker = 20520,
    StudPoker = 20521,
    SplitpotPoker = 20522,
    RedhotPoker = 20523,
    LaundryPole = 20600,
    CarryingPole = 20601,
    OakenPole = 20602,
    IronBar = 20603,
    SteelBar = 20604,
    GigasteelBar = 20605,
    PillarOfStrength = 20606,
    SleepyStick = 20607,
    SlumberStick = 20608,
    DrillerPillar = 20609,
    KillerPillar = 20610,
    Mistick = 20611,
    Optimistick = 20612,
    Ballistick = 20613,
    Sadistick = 20614,
    DragonRod = 20615,
    XenlonRod = 20616,
    Orichalcudgel = 20617,
    KnockoutRod = 20618,
    SenselessStick = 20619,
    CatatonicCosh = 20620,
    ComaCudgel = 20621,
    Boomerang = 20700,
    ReinforcedBoomerang = 20701,
    EdgedBoomerang = 20702,
    CuttingedgeBoomerang = 20703,
    Crucerang = 20704,
    RazorwingBoomerang = 20705,
    RazerwingBoomerang = 20706,
    ErazorwingBoomerang = 20707,
    Swallowtail = 20708,
    Eaglewing = 20709,
    Gustarang = 20710,
    Blusterang = 20711,
    FlametangBoomerang = 20712,
    BanefireBoomerang = 20713,
    Pentarang = 20714,
    Hexarang = 20715,
    Meteorang = 20716,
    Asterang = 20717,
    Stellarang = 20718,
    Galaxarang = 20719,
    StoneClaws = 20800,
    IronClaws = 20801,
    SteelClaws = 20802,
    GigasteelClaws = 20803,
    SacredClaws = 20804,
    RazorClaws = 20805,
    CrowsClaws = 20806,
    KestrelClaws = 20807,
    KiteClaws = 20808,
    Handrills = 20809,
    HammerHandrills = 20810,
    DragonClaws = 20811,
    FireClaws = 20812,
    Combusticlaws = 20813,
    CobraClaws = 20814,
    KingCobraClaws = 20815,
    BeastClaws = 20816,
    BeastmasterClaws = 20817,
    OrichalcumClaws = 20818,
    DragonlordClaws = 20819,
    DragovianClaws = 20820,
    DragovianLordClaws = 20821,
    XenionClaws = 20822,
    PotshotBow = 20900,
    ShortBow = 20901,
    Longbow = 20902,
    HuntersBow = 20903,
    FuddleBow = 20904,
    CheironsBow = 20905,
    HotshotBow = 20906,
    BlowyBow = 20907,
    BillowingBow = 20908,
    BlusteryBow = 20909,
    GreatBow = 20910,
    PurblindBow = 20911,
    BlindingBow = 20912,
    OhnoBow = 20913,
    OdinsBow = 20914,
    AngelsBow = 20915,
    ArchangelsBow = 20916,
    AeonsBow = 20917,
    SeraphsBow = 20918,
    WarriorsShield = 21000,
    ShellShield = 21001,
    KittyShield = 21002,
    CattyShield = 21003,
    LightShield = 21004,
    PlatinumShield = 21005,
    TempestShield = 21006,
    SaintessShield = 21007,
    GoddessShield = 21008,
    RustyShield = 21009,
    BrainDrainer = 21010,
    PsycheSwiper = 21011,
    DevilryDrinker = 21012,
    SoulSucker = 21013,
    SlimeShield = 21014,
    BronzeShield = 21091,
    IronShield = 21092,
    SteelShield = 21093,
    GigasteelShield = 21095,
    MetalSlimeShield = 21190,
    ErdricksShield = 21191,
    ScaleShield = 21192,
    LiquidMetalShield = 21193,
    MetalKingShield = 21194,
    WhiteKnightsShield = 21200,
    EnchantedShield = 21280,
    EtherealShield = 21281,
    EmpoweredShield = 21282,
    MagicShield = 21290,
    LeatherShield = 21291,
    PowerShield = 21292,
    SilverShield = 21294,
    WhiteShield = 21295,
    PotLid = 21296,
    SilverPlatter = 21297,
    GoldPlatter = 21298,
    PlatinumPlatter = 21299,
    FlameShield = 21390,
    DragonShield = 21391,
    BossShield = 21392,
    RuinousShield = 21393,
    OgreShield = 21394,
    IceShield = 21395,
    DarkShield = 21396,
    BigBossShield = 21397,
    MedicinalHerb = 22000,
    StrongMedicine = 22001,
    SpecialMedicine = 22002,
    SuperiorMedicine = 22003,
    AntidotalHerb = 22004,
    StrongAntidote = 22005,
    SpecialAntidote = 22006,
    MoonwortBulb = 22007,
    Softwort = 22008,
    Lunaria = 22009,
    AngelBell = 22010,
    Panacea = 22011,
    PerfectPanacea = 22012,
    YggdrasilLeaf = 22013,
    YggdrasilDew = 22014,
    MagicWater = 22015,
    SagesElixir = 22016,
    ElfinElixir = 22017,
    HolyWater = 22018,
    ChimaeraWing = 22019,
    MystifyingMixture = 22020,
    Coagulant = 22021,
    Tangleweb = 22022,
    SleepingHibiscus = 22023,
    Wakerobin = 22024,
    PartyPopper = 22025,
    FestiveFeast = 22026,
    BlockOChoc = 22027,
    ChoiceChocolate = 22028,
    BasicBiscuits = 22029,
    PoshBiscuits = 22030,
    ChristmasCake = 22031,
    BirthdayCake = 22032,
    RockbombShard = 22033,
    WatchersWings = 22034,
    SagesStone = 22035,
    GleebanGroat = 22036,
    GleebanGuinea = 22037,
    GleebanGoldPiece = 22038,
    MiniMedal = 22039,
    PrettyBetsy = 22041,
    ThiefsKey = 22042,
    MagicKey = 22043,
    UltimateKey = 22044,
    SeedOfLife = 22045,
    SeedOfMagic = 22046,
    SeedOfStrength = 22047,
    SeedOfDeftness = 22048,
    SeedOfAgility = 22049,
    SeedOfDefence = 22050,
    SeedOfSorcery = 22051,
    SeedOfTherapeusis = 22052,
    SeedOfSkill = 22053,
    IronNails = 22070,
    IronOre = 22071,
    PlatinumOre = 22072,
    MythrilOre = 22073,
    Densinium = 22074,
    GoldBar = 22075,
    Orichalcum = 22076,
    HephaestusFlame = 22077,
    Cowpat = 22078,
    HorseManure = 22079,
    SaintsAshes = 22080,
    EnchantedStone = 22081,
    EtherealStone = 22082,
    WingOfBat = 22083,
    AstralPlume = 22084,
    MagicBeastHide = 22085,
    MagicBeastHorn = 22086,
    Slimedrop = 22087,
    ButterflyWing = 22088,
    KittyLitter = 22089,
    GlassFrit = 22090,
    BelleCap = 22091,
    Fisticup = 22092,
    LavaLump = 22093,
    FreshWater = 22094,
    FlurryFeather = 22095,
    RoyalSoil = 22096,
    IceCrystal = 22097,
    Thunderball = 22098,
    Evencloth = 22099,
    BrightenRock = 22100,
    Tortoiseshell = 22101,
    ToadOil = 22102,
    Lambswool = 22103,
    Snakeskin = 22104,
    MankyMud = 22105,
    Corundum = 22106,
    ResetStone = 22107,
    CelestialSkein = 22108,
    SaintedSoma = 22109,
    LucidaShard = 22110,
    AgateOfEvolution = 22111,
    Resurrock = 22112,
    Mirrorstone = 22113,
    Sunstone = 22114,
    Flintstone = 22115,
    Malicite = 22116,
    Slipweed = 22117,
    Thinkincense = 22118,
    Narspicious = 22119,
    Seashell = 22120,
    CrimsonCoral = 22121,
    EmeraldMoss = 22122,
    Finessence = 22123,
    Aggressence = 22124,
    MimicStone = 22125,
    BlarneyStone = 22126,
    PlatinumPick = 22129,
    LittleKey = 22131,
    AngelsTears = 22132,
    Nectar = 22141,
    BirdsongNectar = 22142,
    GrubbyBandage = 22143,
    TechnicolourDreamcloth = 22144,
    KeepsakeRing = 22158,
    Benevolessence = 22159,
    Inny = 22160,
    QuarantombKey = 22162,
    BoduraGrass = 22164,
    SereneNecklace = 22165,
    WyrmlightBow = 22166,
    DrunkenDragon = 22167,
    GittishSeal = 22168,
    Fygg = 22169,
    Friendant = 22170,
    NightmareNurse = 22171,
    Guestbook = 22172,
    EncyclopaediaGittanica = 22173,
    RoyalSeal = 22174,
    Cheermeup = 22175,
    StampCard = 22176,
    DriversLicence = 22177,
    YggdrasilBud = 22178,
    StellarMedicine = 22179,
    BrilliantBiscuits = 22180,
    CrownJewel = 22181,
    DragonsTear = 22182,
    NodsTear = 22183,
    PrayerPearl = 22184,
    TycoonsTrove = 22185,
    LunarDiamond = 22186,
    HocusChimaeraFeather = 22187,
    Duneberry = 22188,
    BrokenBlade = 22189,
    Backscratcher = 22190,
    Hammerfang = 22191,
    MirrorOfReflection = 22192,
    MaxsAxe = 22193,
    TinnyTailFeather = 22194,
    FreezingFeather = 22195,
    WobblyJelly = 22196,
    BloomingdaleBadge = 22197,
    GleebaBadge = 22198,
    AngelFallsBadge = 22199,
    CoffinwellBadge = 22200,
    SnowberianBadge = 22201,
    MoltenMagma = 22202,
    StaffScroll = 22203,
    CatwrightsParcel = 22204,
    bonzerBoomeranging = 22205,
    betterBoomeranging = 22206,
    basicBoomeranging = 22207,
    TeenySanguiniScarf = 22208,
    PinkSanguiniScarf = 22209,
    GenieSanguiniScarf = 22210,
    PackedLunch = 22211,
    CrumpledNote = 22212,
    Goododendron = 22213,
    CrumpledLetter = 22214,
    BeardyWeirdy = 22216,
    TornExamPaper1 = 22217,
    TornExamPaper2 = 22218,
    TornExamPaper3 = 22219,
    DeadMansDagger = 22220,
    PackageFromMa = 22221,
    RagDoll = 22222,
    MagmaliceHandprint = 22223,
    MegaMoaiHeadprint = 22224,
    MementoNecklace = 22225,
    TitanicTincture = 22226,
    LarrrstLetter = 22227,
    Hexite = 22228,
    DrakulordsTooth = 22229,
    HeavenlyHorseshoe = 22230,
    Gratite = 22231,
    PlumStone = 22232,
    ClumpOfCloud = 22233,
    RankenedPhial = 22234,
    Grundies = 22235,
    JewelleryBox = 22246,
    TerrordiseTailFeather = 22247,
    OldRing = 22249,
    wisdomOfTheAncients = 22250,
    Dirtbag = 22251,
    BoneChimer = 22253,
    TurboToadOil = 22255,
    SterlingsWhistle = 22256,
    Evacubell = 22257,
    Chronocrystal = 22258,
    RedOrb = 22259,
    BlueOrb = 22260,
    YellowOrb = 22261,
    GreenOrb = 22262,
    PurpleOrb = 22263,
    SilverOrb = 22264,
    SwordcraftInSummary = 22265,
    ClearSpearTheory = 22266,
    KnifingKnowhow = 22267,
    WandsAndBeyond = 22268,
    WorkingWithWhips = 22269,
    StaffStudies = 22270,
    TheCoreOfTheClaw = 22271,
    FurtherFanmanship = 22272,
    AdvancedAxecraft = 22273,
    HardcoreHammering = 22274,
    TheBoomerangBible = 22275,
    ArcheryForTheAdept = 22276,
    FearsomeFisticuffing = 22277,
    SecretsOfTheShield = 22278,
    WarriorsWorkbook = 22279,
    PriestsPrimer = 22280,
    MagesManual = 22281,
    MartialArtistsManual = 22282,
    ThiefsTheory = 22283,
    MinstrelsManual = 22284,
    GladiatorsManual = 22285,
    PaladinsPrimer = 22286,
    ArmamentalistsAlbum = 22287,
    RangersRevelations = 22288,
    SagesScripture = 22289,
    LuminarysLore = 22290,
    Nothing = 0xffff,
};

struct VocationSet<T, auto IncludeGuardian> {
    if (IncludeGuardian) {
        T guardian;
    }
    T warrior;
    T priest;
    T mage;
    T martial_artist;
    T thief;
    T minstrel;
    T gladiator;
    T armamentalist;
    T paladin;
    T sage;
    T luminary;
    T ranger;
};

bitfield Seeds {
    strength        : 10;
    agility         : 10;
    resiliance      : 10;
    padding         : 2;
    deftness        : 10;
    charm           : 10;
    magical_mending : 10;
    padding         : 2;
    magical_might   : 10;
    max_hp          : 10;
    max_mp          : 10;
    padding         : 2;
};

struct SkillSet<T> {
    T sword_skill;
    T spear_skill;
    T knife_skill;
    T wand_skill;
    T whip_skill;
    T staff_skill;
    T claw_skill;
    T fan_skill;
    T axe_skill;
    T hammer_skill;
    T boomerang_skill;
    T bow_skill;
    T shield_skill;
    T fisticuffs_skill;
    T courage;
    T faith;
    T spellcraft;
    T focus;
    T acquisitiveness;
    T litheness;
    T guts;
    T fource;
    T virtue;
    T enlightenment;
    T je_ne_sais_quoi;
    T ruggedness;
};

bitfield Proficiencies {
    bool sword_skill_dragon_slash_3 : 1;
    bool sword_skill_attack_plus_10_with_sword_7 : 1;
    bool sword_skill_metal_slash_13 : 1;
    bool sword_skill_critical_up_22 : 1;
    bool sword_skill_miracle_slash_35 : 1;
    bool sword_skill_attack_plus_20_with_sword_42 : 1;
    bool sword_skill_falcon_slash_58 : 1;
    bool sword_skill_attack_plus_30_with_sword_76 : 1;
    bool sword_skill_gigaslash_88 : 1;
    bool sword_skill_omnivocational_swordmaster_100 : 1;
    padding : 1;
    bool spear_skill_attack_plus_10_with_spear_7 : 1;
    bool spear_skill_mercurial_thrust_3 : 1;
    bool spear_skill_critical_hit_rate_up_with_spear_35 : 1;
    bool spear_skill_cattle_prod_13 : 1;
    bool spear_skill_attack_plus_20_with_spear_42 : 1;
    bool spear_skill_pressure_pointer_22 : 1;
    bool spear_skill_attack_plus_30_with_spear_76 : 1;
    bool spear_skill_thunder_thrust_58 : 1;
    bool spear_skill_multithrust_88 : 1;
    bool spear_skill_omnivocational_spearmaster_100 : 1;
    padding : 1;
    bool knife_skill_toxic_dagger_3 : 1;
    bool knife_skill_attack_plus_10_with_knife_7 : 1;
    bool knife_skill_fly_swat_13 : 1;
    bool knife_skill_attack_plus_20_with_knife_42 : 1;
    bool knife_skill_victimiser_35 : 1;
    bool knife_skill_critical_hit_rate_up_with_knife_22 : 1;
    bool knife_skill_assassins_stab_58 : 1;
    bool knife_skill_attack_plus_30_with_knife_76 : 1;
    bool knife_skill_hp_hoover_88 : 1;
    bool knife_skill_omnivocational_knifemaster_100 : 1;
    padding : 1;
    bool shield_skill_blockenspiel_6 : 1;
    bool shield_skill_block_chance_plus_2_percent_12 : 1;
    bool shield_skill_defending_champion_18 : 1;
    bool shield_skill_block_chance_plus_2_percent_25 : 1;
    bool shield_skill_immense_defence_32 : 1;
    bool shield_skill_block_chance_plus_2_percent_52 : 1;
    bool shield_skill_magic_mirror_40 : 1;
    padding : 1;
    bool shield_skill_back_atcha_82 : 1;
    bool shield_skill_omnivocational_shieldmaster_100 : 1;
    bool shield_skill_holy_impregnable_66 : 1;
    bool courage_whipping_boy_8 : 1;
    bool courage_natural_strength_plus_10_16 : 1;
    bool courage_whistle_28 : 1;
    bool courage_natural_resilience_plus_20_40 : 1;
    bool courage_body_slam_48 : 1;
    bool courage_natural_strength_plus_30_56 : 1;
    bool courage_morale_masher_70 : 1;
    bool courage_natural_resilience_plus_40_80 : 1;
    bool courage_natural_max_hp_plus_60_90 : 1;
    bool courage_attack_attacker_100 : 1;
    padding : 1;
    bool wand_skill_max_mp_plus_10_with_wand_3 : 1;
    bool wand_skill_antimagic_7 : 1;
    bool wand_skill_mp_absorption_plus_2_percent_with_wand_13 : 1;
    bool wand_skill_beelfreeze_21 : 1;
    bool wand_skill_max_mp_plus_30_with_wand_31 : 1;
    bool wand_skill_caduceus_44 : 1;
    bool wand_skill_mp_absorption_plus_4_percent_with_wand_57 : 1;
    bool wand_skill_max_mp_plus_60_with_wand_70 : 1;
    bool wand_skill_auto_mp_recovery_with_wand_84 : 1;
    bool wand_skill_omnivocational_wandmaster_100 : 1;
    padding : 1;
    bool staff_skill_attack_plus_10_with_staff_3 : 1;
    bool staff_skill_trip_of_a_deathtime_7 : 1;
    bool staff_skill_attack_plus_20_with_staff_35 : 1;
    bool staff_skill_deliverance_22 : 1;
    bool staff_skill_critical_rate_up_with_staff_13 : 1;
    bool staff_skill_party_pooper_42 : 1;
    bool staff_skill_evasion_chance_plus_4_percent_with_staff_58 : 1;
    bool staff_skill_crushed_ice_76 : 1;
    bool staff_skill_attack_plus_30_with_staff_88 : 1;
    bool staff_skill_omnivocational_staffmaster_100 : 1;
    padding : 1;
    bool faith_divination_8 : 1;
    bool faith_natural_magical_mending_plus_20_16 : 1;
    bool faith_benediction_28 : 1;
    bool faith_natural_maxmp_plus_10_40 : 1;
    bool faith_rotstopper_48 : 1;
    bool faith_natural_magical_mending_plus_60_56 : 1;
    bool faith_alma_mater_70 : 1;
    bool faith_natural_max_mp_plus_20_80 : 1;
    bool faith_care_prayer_90 : 1;
    bool faith_natural_magical_mending_plus_100_100 : 1;
    padding : 1;
    bool whip_skill_hypnowhip_3 : 1;
    bool whip_skill_attack_plus_10_with_whip_13 : 1;
    bool whip_skill_lashings_of_love_7 : 1;
    bool whip_skill_attack_plus_20_with_whip_35 : 1;
    bool whip_skill_hit_the_hay_42 : 1;
    bool whip_skill_attack_plus_30_with_whip_58 : 1;
    bool whip_skill_trammel_lash_22 : 1;
    bool whip_skill_schadenfreude_76 : 1;
    bool whip_skill_twin_dragon_lash_88 : 1;
    bool whip_skill_omnivocational_whipmaster_100 : 1;
    padding : 1;
    bool spellcraft_natural_magical_might_plus_20_18 : 1;
    bool spellcraft_wizard_ward_8 : 1;
    bool spellcraft_natural_max_mp_plus_10_38 : 1;
    bool spellcraft_spooky_aura_26 : 1;
    bool spellcraft_critical_spell_rate_up_54 : 1;
    bool spellcraft_focus_pocus_46 : 1;
    bool spellcraft_natural_max_mp_plus_20_88 : 1;
    bool spellcraft_channel_anger_68 : 1;
    bool spellcraft_natural_magical_might_plus_60_78 : 1;
    bool spellcraft_natural_magical_might_plus_100_100 : 1;
    padding : 1;
    bool claw_skill_propeller_blade_3 : 1;
    bool claw_skill_attack_plus_10_with_claw_7 : 1;
    bool claw_skill_can_opener_13 : 1;
    bool claw_skill_critical_hit_rate_up_with_claw_22 : 1;
    bool claw_skill_flailing_nails_35 : 1;
    bool claw_skill_attack_plus_20_with_claw_42 : 1;
    bool claw_skill_hardclaw_58 : 1;
    bool claw_skill_attack_plus_30_with_claw_76 : 1;
    bool claw_skill_rake_n_break_88 : 1;
    bool claw_skill_omnivocational_clawmaster_100 : 1;
    padding : 1;
    bool fan_skill_attack_plus_10_with_fan_7 : 1;
    bool fan_skill_flower_power_3 : 1;
    bool fan_skill_attack_plus_20_with_fan_42 : 1;
    bool fan_skill_reverse_cycle_13 : 1;
    bool fan_skill_critical_hit_rate_up_with_fan_22 : 1;
    bool fan_skill_water_slaughterer_35 : 1;
    bool fan_skill_attack_plus_30_with_fan_76 : 1;
    bool fan_skill_schizofanic_58 : 1;
    bool fan_skill_fan_dango_88 : 1;
    bool fan_skill_omnivocational_fanmaster_100 : 1;
    padding : 1;
    bool fisticuffs_skill_attack_plus_10_with_fist_7 : 1;
    bool fisticuffs_skill_stones_throw_3 : 1;
    bool fisticuffs_skill_critical_hit_rate_up_with_fist_18 : 1;
    bool fisticuffs_skill_wind_sickles_12 : 1;
    bool fisticuffs_skill_evasion_chance_plus_4_percent_with_fist_30 : 1;
    bool fisticuffs_skill_knuckle_sandwich_25 : 1;
    bool fisticuffs_skill_attack_plus_30_with_fist_60 : 1;
    bool fisticuffs_skill_multifists_42 : 1;
    bool fisticuffs_skill_boulder_toss_77 : 1;
    bool fisticuffs_skill_attack_plus_60_with_fist_100 : 1;
    padding : 1;
    bool focus_war_cry_4 : 1;
    bool focus_natural_agility_plus_10_10 : 1;
    bool focus_psyche_up_16 : 1;
    bool focus_natural_strength_plus_10_22 : 1;
    bool focus_mens_sana_32 : 1;
    bool focus_natural_max_hp_plus_30_42 : 1;
    bool focus_mind_over_matter_55 : 1;
    bool focus_natural_agility_plus_30_68 : 1;
    bool focus_meditation_82 : 1;
    bool focus_natural_agility_plus_60_100 : 1;
    padding : 1;
    bool acquisitiveness_natural_deftness_plus_20_4 : 1;
    bool acquisitiveness_half_inch_10 : 1;
    bool acquisitiveness_natural_agility_plus_20_16 : 1;
    bool acquisitiveness_pitfall_22 : 1;
    bool acquisitiveness_natural_max_hp_plus_20_32 : 1;
    bool acquisitiveness_nose_for_treasure_42 : 1;
    bool acquisitiveness_natural_deftness_plus_40_55 : 1;
    bool acquisitiveness_eye_for_trouble_68 : 1;
    bool acquisitiveness_natural_agility_plus_40_82 : 1;
    bool acquisitiveness_treasure_eye_land_100 : 1;
    padding : 1;
    bool litheness_hot_lick_4 : 1;
    bool litheness_spry_in_crisis_10 : 1;
    bool litheness_pratfall_16 : 1;
    bool litheness_natural_charm_plus_30_22 : 1;
    bool litheness_sobering_slap_32 : 1;
    bool litheness_natural_magical_might_plus_30_42 : 1;
    bool litheness_tap_dance_55 : 1;
    bool litheness_natural_magical_mending_plus_30_68 : 1;
    bool litheness_have_a_ball_82 : 1;
    bool litheness_natural_deftness_plus_50_100 : 1;
    padding : 1;
    bool axe_skill_helm_splitter_35 : 1;
    bool axe_skill_attack_plus_10_with_axe_7 : 1;
    bool axe_skill_poplar_toppler_3 : 1;
    bool axe_skill_attack_plus_20_with_axe_42 : 1;
    bool axe_skill_parallax_13 : 1;
    bool axe_skill_critical_hit_rate_up_with_axe_22 : 1;
    bool axe_skill_hatchet_man_58 : 1;
    bool axe_skill_attack_plus_30_with_axe_76 : 1;
    bool axe_skill_axes_of_evil_88 : 1;
    bool axe_skill_omnivocational_axe_master_100 : 1;
    padding : 1;
    bool hammer_skill_attack_plus_10_with_hammer_7 : 1;
    bool hammer_skill_heart_breaker_3 : 1;
    bool hammer_skill_critical_hit_rate_up_with_hammer_22 : 1;
    bool hammer_skill_penny_pincher_13 : 1;
    bool hammer_skill_attack_plus_20_with_hammer_42 : 1;
    bool hammer_skill_bagsy_last_35 : 1;
    bool hammer_skill_attack_plus_30_with_hammer_76 : 1;
    bool hammer_skill_monster_masher_58 : 1;
    bool hammer_skill_crackerwhack_88 : 1;
    bool hammer_skill_omnivocational_hammermaster_100 : 1;
    padding : 1;
    bool guts_natural_max_hp_plus_10_4 : 1;
    bool guts_clap_trap_10 : 1;
    bool guts_natural_strength_plus_10_16 : 1;
    bool guts_double_up_22 : 1;
    bool guts_natural_max_hp_plus_20_32 : 1;
    bool guts_blind_mans_biff_68 : 1;
    bool guts_natural_strength_plus_30_55 : 1;
    bool guts_double_edged_slash_42 : 1;
    bool guts_natural_max_hp_plus_30_82 : 1;
    bool guts_feel_the_burn_100 : 1;
    padding : 1;
    bool bow_skill_attack_plus_10_with_bow_7 : 1;
    bool bow_skill_conjury_conductor_3 : 1;
    bool bow_skill_attack_plus_20_with_bow_42 : 1;
    bool bow_skill_flutter_disaster_13 : 1;
    bool bow_skill_critical_hit_rate_up_with_bow_22 : 1;
    bool bow_skill_needle_shot_35 : 1;
    bool bow_skill_attack_plus_30_with_bow_76 : 1;
    bool bow_skill_rain_of_pain_58 : 1;
    bool bow_skill_hallowed_arrow_88 : 1;
    bool bow_skill_omnivocational_bowmaster_100 : 1;
    padding : 1;
    bool fource_fire_fource_4 : 1;
    bool fource_natural_strength_plus_10_10 : 1;
    bool fource_frost_fource_16 : 1;
    bool fource_natural_resilience_plus_20_22 : 1;
    bool fource_gale_fource_32 : 1;
    bool fource_natural_charmplus_10_42 : 1;
    bool fource_funeral_fource_55 : 1;
    bool fource_natural_magical_might_plus_30_68 : 1;
    bool fource_life_fource_82 : 1;
    bool fource_natural_max_hp_plus_30_100 : 1;
    padding : 1;
    bool virtue_pincushion_4 : 1;
    bool virtue_natural_resilience_plus_10_10 : 1;
    bool virtue_h_pathy_16 : 1;
    bool virtue_natural_magical_mendingplus_30_22 : 1;
    bool virtue_m_pathy_32 : 1;
    bool virtue_natural_resilience_plus_20_42 : 1;
    bool virtue_selflessness_55 : 1;
    bool virtue_natural_resilience_plus_20_68 : 1;
    bool virtue_forbearance_82 : 1;
    bool virtue_maximum_hp_plus_80_100 : 1;
    padding : 1;
    bool boomerang_skill_crosscutter_throw_3 : 1;
    bool boomerang_skill_attack_plus_10_with_boomerang_13 : 1;
    bool boomerang_skill_power_throw_7 : 1;
    bool boomerang_skill_attack_plus_20_with_boomerang_35 : 1;
    bool boomerang_skill_ooze_bruiser_22 : 1;
    bool boomerang_skill_attack_plus_30_with_boomerang_76 : 1;
    bool boomerang_skill_starburst_throw_42 : 1;
    bool boomerang_skill_firebird_throw_58 : 1;
    bool boomerang_skill_metalicker_88 : 1;
    bool boomerang_skill_omnivocational_rangmaster_100 : 1;
    padding : 1;
    bool enlightenment_natural_magical_mending_plus_20_4 : 1;
    bool enlightenment_jacks_knack_10 : 1;
    bool enlightenment_natural_magical_might_plus_20_16 : 1;
    bool enlightenment_right_as_rain_22 : 1;
    bool enlightenment_natural_magical_mending_plus_40_32 : 1;
    bool enlightenment_disruptive_wave_42 : 1;
    bool enlightenment_natural_magical_might_plus_40_55 : 1;
    bool enlightenment_caster_sugar_68 : 1;
    bool enlightenment_natural_max_mp_plus_60_82 : 1;
    bool enlightenment_mp_consumption__25_percent_100 : 1;
    padding : 1;
    bool je_ne_sais_quoi_natural_charm_plus_10_4 : 1;
    bool je_ne_sais_quoi_autograph_10 : 1;
    bool je_ne_sais_quoi_natural_agility_plus_20_16 : 1;
    bool je_ne_sais_quoi_scandal_eyes_22 : 1;
    bool je_ne_sais_quoi_natural_max_hp_plus_20_32 : 1;
    bool je_ne_sais_quoi_extreme_makeover_42 : 1;
    bool je_ne_sais_quoi_natural_charm_plus_20_55 : 1;
    bool je_ne_sais_quoi_eyes_on_me_68 : 1;
    bool je_ne_sais_quoi_natural_charm_plus_30_82 : 1;
    bool je_ne_sais_quoi_disco_stew_100 : 1;
    padding : 1;
    bool ruggedness_mercy_16 : 1;
    bool ruggedness_natural_deftness_plus_10_10 : 1;
    bool ruggedness_soothe_sayer_4 : 1;
    bool ruggedness_natural_agility_plus_20_22 : 1;
    bool ruggedness_vanish_32 : 1;
    bool ruggedness_natural_resilience_plus_20_42 : 1;
    bool ruggedness_mist_me_55 : 1;
    bool ruggedness_natural_deftness_plus_20_68 : 1;
    bool ruggedness_wolf_whistle_82 : 1;
    bool ruggedness_natural_deftness_plus_60_100 : 1;
};

struct Name {
    char chars[10];
};

bitfield CharacterColors {
    gender : 1;
    skinColor : 3;
    eyeColor : 4;
    hairColor : 4;
    padding : 4; // unknown?
};

struct PreviouslyEquippedArmorSet {
    Item weapon;
    Item torso;
    Item shield;
    Item head;
    Item arms;
    Item trousers;
    Item shoes;
    Item accessory;
};

struct Character {
    padding[2]; // unknown data
    VocationSet<u8, true> levels;
    VocationSet<u8, true> revocations;
    VocationSet<u32, true> expirence_pts;
    Vocation current_vocation;
    padding[7]; // unknown data
    VocationSet<Seeds, true> seeds;
    padding[3]; // unknown data
    SkillSet<u8> skill_point_allocations;
    padding[9]; // unknown data
    Proficiencies proficiencies;
    padding[2]; // unknown data
    Name name;
    padding[22]; // unknown data (max mp hp seems to be in here?)
    Item equippedTorsoArmor;
    Item equippedTrousers;
    u8 faceType; //TODO: enum for this? valid/dlc/etc?
    padding[1]; // seems to always be 0x23?
    u8 hairStyle; //TODO: enum?
    padding[1]; // seems to always be 0x23?
    Item equippedArmArmor;
    Item equippedFootwear;
    Item equippedHeadware;
    Item equippedWeapon;
    Item equippedShield;
    Item equippedAccessory;
    CharacterColors;
    padding[2]; // unknown...
    u16 width;
    u16 height;
    VocationSet<PreviouslyEquippedArmorSet, false>;
};

struct HeldItems {
    Item items[8];
    padding[2]; // should always be 0?
};

bitfield SpecialGuests {
    padding        : 1;
    bool Princeton : 1;
    bool Princessa : 1;
    bool Alena     : 1;
    bool Kiryl     : 1;
    bool Borya     : 1;
    bool Meena     : 1;
    bool Maya      : 1;
    bool Torneko   : 1;
    bool Ragnar    : 1;
    bool Bianca    : 1;
    bool Nera      : 1;
    bool Debora    : 1;
    bool Milly     : 1;
    bool Carver    : 1;
    bool Ashlynn   : 1;
    bool Kiefer    : 1;
    bool Maribel   : 1;
    bool Jessica   : 1;
    bool Angelo    : 1;
    bool Yangus    : 1;
    bool Trode     : 1;
    bool Morrie    : 1;
    bool Fleurette : 1;
    padding        : 8;
};

bitfield VisitedLocations {
    padding : 1;
    bool Angel_falls       : 1;
    bool Zere              : 1;
    bool Stornway          : 1;
    bool Coffinwell        : 1;
    bool Alltrades_abbey   : 1;
    bool Porth_llaffan     : 1;
    bool Slurry_quay       : 1;
    bool Dourbridge        : 1;
    bool Zere_rocks        : 1;
    bool Bloomingdale      : 1;
    bool Gleeba            : 1;
    bool Batsureg          : 1;
    bool Swinedimples      : 1;
    bool Wormwood_creek    : 1;
    bool Upover            : 1;
    bool The_magmaroo      : 1;
    bool The_gortress      : 1;
    bool Gittingham_palace : 1;
    padding : 5;
};

bitfield LearnedPartyTricks {
    padding : 2;
    bool Pray                : 1;
    bool Pirouette           : 1;
    bool Bow                 : 1;
    bool Belly_Dance         : 1;
    bool Royal_Regards       : 1;
    bool Swinedimples_Salute : 1;
    bool Capns_Curtsy        : 1;
    bool Sultry_Dance        : 1;
    bool Weird_Dance         : 1;
    bool Wallop              : 1;
    bool Cheer               : 1;
    bool Provoke             : 1;
    bool Salute              : 1;
    bool Inspiration         : 1;
    bool Professors_Pose     : 1;
    padding : 7;
};

bitfield UnlockableVocations {
    padding : 6;
    bool gladiator     : 1;
    bool armamentalist : 1;
    bool paladin       : 1;
    bool sage          : 1;
    bool luminary      : 1;
    bool ranger        : 1;
    padding : 6;
};

bitfield GuestYearGrotto {
    check_in_year  : 7;
    bool holding_grotto : 1;
};

enum GuestLocation : u8 {
    Level1Left = 2,
    Level2Left = 3,
    Level2Right = 4,
    Level3Left = 5,
    Level3Right = 6,
    RoyalSuitesRight = 9,
    RoyalSuitesLeft = 10,
};

bitfield GuestLocationVocation {
    Vocation vocation : 4;
    GuestLocation location : 4;
};

bitfield GuestCheckInLevel {
    level : 7;
    month : 4;
    day : 5;
};

bitfield GuestIndex {
    padding : 2;
    index : 30;
};

struct CanvasedGuest {
    Name name;
    padding[1];
    GuestYearGrotto;
    GuestLocationVocation;
    padding[2]; // GuestCheckInLevel;
    GuestIndex;
};

struct SaveSlot {
    char magic_string[16];
    u32 checksum_a;
    padding[112]; // unknown data
    u32 checksum_b;
    Character characters[13];
    padding[6];
    HeldItems party_held_items[4];
    padding[3798]; // very unknown data lol...
    u32 gold_on_hand;
    u32 gold_in_bank;
    padding[4];
    u32 minimedals_given;
    padding[64];
    SpecialGuests;
    padding[256];
    VisitedLocations;
    padding[317];
    LearnedPartyTricks;
    padding[165];
    UnlockableVocations;
    padding[3921];
    CanvasedGuest guests[30];
};

SaveSlot saveSlot @ 0x0;